#!/bin/sh

echo 'Deploying'
echo 'Packaging'
zip -r movie.zip /var/lib/jenkins/workspace/movie
echo "Copy"
mkdir /home/ec2-user/movieapp
cp -r /var/lib/jenkins/workspace/movie/movie.zip /home/ec2-user/movieapp
unzip movie.zip
# echo 'npm installation'
# npm install
# echo 'starting pm'
# /home/ec2-user/.nvm/versions/node/v6.11.2/lib/node_modules/pm2/bin/pm2 start /var/lib/jenkins/workspace/movie/app.js
echo 'exiting'
